version: '3.8'

services:
  blueprint-service:
    build:
      context: blueprint-service/
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    networks:
      - platform_network

#  other-blueprint-service:
#    build:
#      context: blueprint-service/
#      dockerfile: Dockerfile
#    environment:
#      - server_port=8101
#      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
#      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
#      - AWS_REGION=${AWS_REGION}
#    ports:
#      - "8101:8101"
#    networks:
#      - platform_network

  database-restoration-service:
    build:
      context: database-restoration-service/
      dockerfile: Dockerfile
    ports:
      - "8200:8200"
    environment:
      - PGPASSWORD=postgres
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    networks:
      - platform_network

  metadata-extraction-service:
    build:
      context: metadata-extraction-service/
      dockerfile: Dockerfile
    ports:
      - "8300:8300"
    networks:
      - platform_network

networks:
  platform_network:
    external: true