version: '3.8'

services:
  blueprint-service:
    build:
      context: blueprint-service/
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    networks:
      - platform_network

  database-restoration-service:
    build:
      context: database-restoration-service/
      dockerfile: Dockerfile
    ports:
      - "8200:8200"
    environment:
      - PGPASSWORD={POSTGRES_PASSWORD}
    networks:
      - platform_network

  metadata-extraction-service:
    build:
      context: metadata-extraction-service/
      dockerfile: Dockerfile
    ports:
      - "8300:8300"
    networks:
      - platform_network

networks:
  platform_network:
    external: true