import os
from dotenv import load_dotenv

load_dotenv()

RESTORATION_SERVICE_URL = os.getenv('RESTORATION_SERVICE_URL')
CREATE_MIRROR_ENDPOINT = os.getenv('CREATE_MIRROR_ENDPOINT')

ANONYMISATION_FRAGMENTS_BUCKET = os.getenv("ANONYMISATION_FRAGMENTS_BUCKET")
ANONYMISATION_SCRIPTS_BUCKET = os.getenv("ANONYMISATION_SCRIPTS_BUCKET")
FRAGMENTS_MERGER_LAMBDA = os.getenv("FRAGMENTS_MERGER_LAMBDA")

MONGODB_CONNECTION_URI = os.getenv('MONGODB_CONNECTION_URI')

FRAGMENTS_URL = os.getenv('FRAGMENTS_URL')
